<?xml version="1.0" encoding="utf-8"?><Database Name="myPractise" Class="DataClassesAssDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-Q4N5U6Q;Initial Catalog=myPractise;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="myPractiseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_user" Member="tbl_users">
    <Type Name="tbl_user">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="family_name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="postal_code" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>